[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "termilyrics"
version = "0.0.2"
description = "A terminal-based tool to synchronize lyrics effortlessly."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "syncedlyrics>=0.7",
    "Pillow>=10.0",
    "PyYAML>=6.0",
    "youtube-transcript-api>=0.6"
]

[tool.setuptools]
packages = ["lyrics_sync"]

[project.scripts]
termilyrics = "lyrics_sync.main:main"
